actuticket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('', include('ticket.urls')),
]

ticket/urls.py
from django.urls import path

from ticket import views

urlpatterns = [
    path('', views.MainView.as_view(), name="main"),
    path('add/', views.AddTicketView.as_view(), name="add_ticket"),
    path('ticket/<ticket_id>', views.TicketDetailView.as_view(), name="ticket_detail"),
    path('ticket/undertake/<ticket_id>', views.UndertakeTicketView.as_view(), name="undertake_ticket"),
    path('ticket/close/<ticket_id>', views.CloseTicketView.as_view(), name="close_ticket"),
    path('ticket/comment/<ticket_id>', views.AddCommentView.as_view(), name="add_comment"),
]

ticket/models.py
from django.conf import settings
from django.db import models
from datetime import date

STATUS = (
    (1, "new"),
    (2, "in progress"),
    (3, "closed"),
)


class Model(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return f"{self.name}"


class Type(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return f"{self.name}"


class Ticket(models.Model):
    title = models.CharField(max_length=128, verbose_name="run title")
    model = models.ManyToManyField(Model)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    version = models.CharField(max_length=128)
    year = models.PositiveIntegerField(default=date.today().year, verbose_name="reporting year")
    month = models.PositiveIntegerField(default=date.today().month-1, verbose_name="reporting month")
    deadline = models.DateTimeField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="create_user")
    created_at = models.DateTimeField()
    undertook_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="undertake_user", null=True)
    undertook_at = models.DateTimeField(null=True)
    closed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="close_user", null=True)
    closed_at = models.DateTimeField(null=True)
    status = models.IntegerField(choices=STATUS, default=1)
    information = models.TextField(verbose_name="additional information", null=True, blank=True)

    class Meta:
        ordering = ["-id"]


class Comment(models.Model):
    written_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="write_user")
    written_at = models.DateTimeField()
    message = models.TextField()
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-written_at"]

ticket/forms.py
from django import forms

from ticket import models


class TicketForm(forms.ModelForm):
    class Meta:
        model = models.Ticket
        fields = ("title", "model", "type", "version", "year", "month", "deadline", "information")
        widgets = {
            "deadline": forms.DateInput(attrs={"type": "date"}),
            "model": forms.CheckboxSelectMultiple(),
        }
        help_texts = {
            "title": "e.g. sensitivities or proxy",
            "information": "e.g. path to the zip file with assumptions",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ("message", )

ticket/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.html import strip_tags
from django.views import View

from ticket import forms, models
from .tasks import send_mail_to_all
from ticket.utils import utils


DOMAIN = settings.DEFAULT_DOMAIN


class MainView(LoginRequiredMixin, View):
    """Main page of the app with the list of new tickets."""
    def get(self, request):
        tickets = models.Ticket.objects.all()

        paginator = Paginator(tickets, 15)
        page = request.GET.get("page")

        try:
            tickets = paginator.page(page)
        except PageNotAnInteger:
            tickets = paginator.page(1)
        except EmptyPage:
            tickets = paginator.page(paginator.num_pages)

        return render(request, "ticket/main.html", {"page": page, "tickets": tickets})


class AddTicketView(LoginRequiredMixin, View):
    """
    Form to add a new ticket.

    The form uses save_m2m() because it has many-to-many relationship with models.
    The users are informed about the new ticket by e-mail (using celery to avoid long waiting time).
    """
    def get(self, request):
        initial_dict = {
            "model": models.Model.objects.all()
        }

        form = forms.TicketForm(initial=initial_dict)
        return render(request, "ticket/ticket_form.html", {"form": form})

    def post(self, request):
        form = forms.TicketForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.created_by = request.user
            ticket.created_at = timezone.now()
            ticket.save()
            form.save_m2m()

            # Show success message
            messages.success(request, f"You have added ticket #{ticket.id}")

            # Inform users by e-mail
            subject = f"actuticket | new ticket {ticket.id} ({ticket.title})"
            ctx = {"ticket": ticket, "domain": DOMAIN}
            html_message = render_to_string("email/add-ticket.html", ctx)
            plain_message = strip_tags(html_message)
            send_mail_to_all.delay(subject, plain_message, html_message)

            return redirect(reverse_lazy("main"))
        return render(request, "ticket/ticket_form.html", {"form": form})


class TicketDetailView(LoginRequiredMixin, View):
    """View with ticket's details."""
    def get(self, request, ticket_id):
        ticket = get_object_or_404(models.Ticket, id=ticket_id)
        return render(request, "ticket/ticket_detail.html", {"ticket": ticket})


class UndertakeTicketView(LoginRequiredMixin, View):
    """View to undertake ticket."""
    def get(self, request, ticket_id):
        ticket = get_object_or_404(models.Ticket, id=ticket_id)
        ticket.undertook_by = request.user
        ticket.undertook_at = timezone.now()
        ticket.status = 2
        ticket.save()

        # Show success message
        messages.success(request, f"You have undertaken ticket #{ticket.id}")

        # Inform users by e-mail
        subject = f"actuticket | ticket {ticket.id} ({ticket.title}) is undertaken"
        good_luck = utils.generate_good_luck()
        ctx = {"ticket": ticket, "good_luck": good_luck, "domain": DOMAIN}
        html_message = render_to_string("email/undertake-ticket.html", ctx)
        plain_message = strip_tags(html_message)
        send_mail_to_all.delay(subject, plain_message, html_message)

        return redirect("ticket_detail", ticket.id)


class CloseTicketView(LoginRequiredMixin, View):
    """View to close ticket."""
    def get(self, request, ticket_id):
        ticket = get_object_or_404(models.Ticket, id=ticket_id)
        if ticket.status != 2:
            return redirect("ticket_detail", ticket.id)

        ticket.closed_by = request.user
        ticket.closed_at = timezone.now()
        ticket.status = 3
        ticket.save()

        # Show success message
        messages.success(request, f"You have closed ticket #{ticket.id}")

        # Inform users by e-mail
        subject = f"actuticket | ticket {ticket.id} ({ticket.title}) is closed"
        good_job = utils.generate_good_job()
        ctx = {"ticket": ticket, "good_job": good_job, "domain": DOMAIN}
        html_message = render_to_string("email/close-ticket.html", ctx)
        plain_message = strip_tags(html_message)
        send_mail_to_all.delay(subject, plain_message, html_message)

        return redirect("ticket_detail", ticket.id)


class AddCommentView(LoginRequiredMixin, View):
    """Form to add comment to a ticket."""
    def get(self, request, ticket_id):
        form = forms.CommentForm
        return render(request, "ticket/comment_form.html", {"form": form})

    def post(self, request, ticket_id):
        ticket = get_object_or_404(models.Ticket, id=ticket_id)
        form = forms.CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.written_by = request.user
            comment.written_at = timezone.now()
            comment.ticket = ticket
            comment.save()

            # Show success message
            messages.success(request, f"You have commented ticket #{ticket.id}")

            # Inform users by e-mail
            subject = f"actuticket | ticket {ticket.id} ({ticket.title}) has a new comment"
            ctx = {"comment": comment, "domain": DOMAIN}
            html_message = render_to_string("email/comment-ticket.html", ctx)
            plain_message = strip_tags(html_message)
            send_mail_to_all.delay(subject, plain_message, html_message)

            return redirect("ticket_detail", ticket.id)
        return redirect("main", ticket.id)

ticket/templates/ticket/comment_form.html
{% extends "base.html" %}
{% block content %}

    <h1>Add comment to ticket</h1>
    <div class="brick">
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <div class="vertical-center">
                <button type="submit" class="button green-button">Add new comment</button>
            </div>
        </form>
    </div>

{% endblock %}

ticket/templates/ticket/main.html
{% extends "base.html" %}

{% block content %}

    <div class="vertical-center">
        <a href='{% url "add_ticket" %}' class="button green-button big-button">Add new ticket</a>
    </div>

    <table>
        <tr>
            <th>ID</th>
            <th>Period</th>
            <th>Title</th>
            <th>Deadline</th>
            <th>Status</th>
            <th>Person</th>
            <th>Time</th>
        </tr>

        {% for ticket in tickets %}
        <tr style='cursor: pointer;' onclick="window.location='{% url "ticket_detail" ticket.id %}';">
            <td>{{ ticket.id }}</td>
            <td>{{ ticket.year}}{{ ticket.month|stringformat:"02d" }}</td>
            <td>{{ ticket.title }}</td>
            <td>{{ ticket.deadline|date:"Y-m-d" }}</td>
            {% if ticket.status == 1 %}
                <td style="color: rgba(220, 53, 69, 0.75); font-weight: bold;">{{ ticket.get_status_display }}</td>
                <td>{{ ticket.created_by.first_name }}</td>
                <td>{{ ticket.created_at|date:'Y-m-d H:i' }}</td>
            {% elif ticket.status == 2 %}
                <td style="color: rgba(255, 121, 0, 0.75); font-weight: bold;">{{ ticket.get_status_display }}</td>
                <td>{{ ticket.undertook_by.first_name }}</td>
                <td>{{ ticket.undertook_at|date:'Y-m-d H:i' }}</td>
            {% elif ticket.status == 3 %}
                <td style="color: rgba(11, 102, 35, 0.75); font-weight: bold;">{{ ticket.get_status_display }}</td>
                <td>{{ ticket.closed_by.first_name }}</td>
                <td>{{ ticket.closed_at|date:'Y-m-d H:i' }}</td>
            {% endif %}

        </tr>
        {% endfor %}
    </table>

    {% include "ticket/pagination.html" with page=tickets %}
</div>

{% endblock %}

ticket/templates/ticket/pagination.html
<div class="pagination vertical-center">
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}"><div class="pagination-arrow">&laquo;</div></a>
    {% endif %}

<div>Page {{ page.number }} of {{ page.paginator.num_pages }}</div>

{% if page.has_next %}
    <a href="?page={{ page.next_page_number }}"><div class="pagination-arrow">&raquo;</div></a>
{% endif %}

ticket/templates/ticket/ticket_detail.html
{% extends "base.html" %}
{% block content %}

    <h1>{{ ticket.title }}</h1>
    <div class="brick">
        <p>
            <span class="label">Ticket ID</span><br>
            <span>{{ ticket.id }}</span>
        </p>

        <p>
            <span class="label">Status</span><br>
            {% if ticket.status == 1 %}
                <span style="color: rgba(220, 53, 69, 0.75); font-weight: bold;">{{ ticket.get_status_display }}</span>
            {% elif ticket.status == 2 %}
                <span style="color: rgba(255, 121, 0, 0.75); font-weight: bold;">{{ ticket.get_status_display }}</span>
            {% elif ticket.status == 3 %}
                <span style="color: rgba(11, 102, 35, 0.75); font-weight: bold;">{{ ticket.get_status_display }}</span>
            {% endif %}
        </p>

        <p>
            <span class="label">Period</span><br>
            <span>{{ ticket.year }}{{ ticket.month|stringformat:"02d" }}</span>
        </p>

        <p>
            <span class="label">Models</span><br>
            <ul>
                {% for model in ticket.model.all %}
                    <li>{{ model }}</li>
                {% endfor %}
            </ul>
        </p>

        <p>
            <span class="label">Type</span><br>
            <span>{{ ticket.type }}</span>
        </p>

        <p>
            <span class="label">Version</span><br>
            <span>{{ ticket.version }}</span>
        </p>

        <p>
            <span class="label">Deadline</span><br>
            <span>{{ ticket.deadline|date:'Y-m-d' }}</span>
        </p>

        <p>
            <span class="label">Additional information</span><br>
            <span>{{ ticket.information|linebreaks }}</span>
        </p>

        <p>
            <span class="label">History</span><br>
            <ul>
                <li>{{ ticket.created_at|date:'Y-m-d H:i' }} created by
                    {{ ticket.created_by.first_name }} {{ ticket.created_by.last_name }}</li>
            {% if ticket.status > 1 %}
                <li>{{ ticket.undertook_at|date:'Y-m-d H:i' }} undertook by
                    {{ ticket.undertook_by.first_name }} {{ ticket.undertook_by.last_name }}</li>
            {% endif %}
            {% if ticket.status > 2 %}
                <li>{{ ticket.closed_at|date:'Y-m-d H:i' }} closed by
                    {{ ticket.closed_by.first_name }} {{ ticket.closed_by.last_name }}</li>
            {% endif %}
            </ul>
        </p>

        {% if ticket.status == 1 %}
            <div class="vertical-center">
                <a href="{% url 'undertake_ticket' ticket.id %}" class="button green-button">Undertake task</a>
            </div>
        {% endif %}

        {% if ticket.status == 2 %}
            <div class="vertical-center">
                <a href="{% url 'close_ticket' ticket.id %}" class="button green-button">Close ticket</a>
            </div>
        {% endif %}
        <br>

        <hr>

        <h2>Comments</h2>

        <a href="{% url 'add_comment' ticket.id %}" class="button gray-button">Add comment</a>

        {% for comment in ticket.comment_set.all %}
            <p>
                <span class="label">{{ comment.written_at|date:'Y-m-d H:i' }} by {{ comment.written_by }}</span><br>
                <span>{{ comment.message|linebreaks }}</span>
            </p>
        {% endfor %}
    </div>

{% endblock %}

ticket/templates/ticket/ticket_form.html
{% extends "base.html" %}
{% block content %}

    <h1>Add new ticket</h1>
    <div class="brick">
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <div class="vertical-center">
                <button type="submit" class="button green-button">Add new ticket</button>
            </div>
        </form>
    </div>

{% endblock %}